### ISSUE TITLE
Extract lat/long coordinates from WKT

### ISSUE THREAD

**Issue by sckott** [ropensci/wicket#10]
Forgot about a use case I need. 

* Input: WKT (polygon in most cases at least for me)
* Output: a `data.frame`, one col for lat and one col for long

Of course there can be other arrangements, sometimes WKT 3D or with altitude, but packages I'll use this pkg in won't be dealing with that

**Comment by Ironholds** [comment]
Can you give an example of the sort of input data you'd be talking about and the expected output?

**Comment by sckott** [comment]
totes, 

`POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))` 

to 

```r
lon lat
30   10
40   40
20   40
10   20
30   10
```

this seems relatively simple to just strsplit or something, but i doubt that would be robust, and surely you can do faster dropping down to C

**Comment by Ironholds** [comment]
Want it vectorised so we end up with a list of data.frames, I assume?

**Comment by sckott** [comment]
yes

**Comment by Ironholds** [comment]
What types do you want supported?

**Comment by Ironholds** [comment]
>wkt_coords(("POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))"))
[[1]]
  lon lat
1  30  10
2  40  40
3  20  40
4  10  20
5  30  10

**Comment by sckott** [comment]
yeah, just POLYGON for now

**Comment by Ironholds** [comment]
And up as wkt_coords. Give it a test?

**Comment by sckott** [comment]
this `POLYGON ((35 10, 45 45, 15 40, 10 20, 35 10), (20 30, 35 35, 30 20, 20 30))`

which yields this visually

<img width="927" alt="screen shot 2017-01-07 at 3 53 38 pm" src="https://cloud.githubusercontent.com/assets/577668/21746173/7c2b933e-d4f1-11e6-90bc-afd0bdbdae0e.png">


but `wkt_coords` only got the set of points from the first polygon

```r
wicket::wkt_coords('POLYGON ((35 10, 45 45, 15 40, 10 20, 35 10), (20 30, 35 35, 30 20, 20 30))')
#> [[1]]
#>   lon lat
#> 1  35  10
#> 2  45  45
#> 3  15  40
#> 4  10  20
#> 5  35  10
```

**Comment by Ironholds** [comment]
Because it's only looking at the outer edges. How would you like inner and outer represented? Do you literally just want every point from inner or outer polygon edges shoved into a df? (and in any particular order?)

**Comment by sckott** [comment]
Maybe label each df as inner or outer?

**Comment by Ironholds** [comment]
Well, then you'll have a list of lists of data.frames, because it's currently one-data-frame-per-wkt-object not per-edge.

**Comment by Ironholds** [comment]
I mean, I could probably wrangle it together into a single data.frame for the entire thing of:

1. Element
2. Layer
3. Lat
4. Lng

Iff you'd like.

**Comment by sckott** [comment]
what would that look like?

**Comment by Ironholds** [comment]
wicket::wkt_coords('POLYGON ((35 10, 45 45, 15 40, 10 20, 35 10), (20 30, 35 35, 30 20, 20 30))')
#>
#>    entry layer lon lat
#> 1  1 outer 35  10
#> 2  1 outer 45  45
#> 3  1 outer 15  40
#> 4  1 outer 10  20
#> 5  1 outer 35  10

...I guess. The other options are smushing everything in inner and outer layers into a single data.frame and tagging them, and ending up with a list of lists of dfs.

**Comment by sckott** [comment]
I don't know. If one makes more sense to you just go with that

**Comment by Ironholds** [comment]
Hey, you're the one dealing with the output data! :)

**Comment by sckott** [comment]
sorry. 

> The other options are smushing everything in inner and outer layers into a single data.frame and tagging them, and ending up with a list of lists of dfs.

So this would be a separate df for each polygon?  So `'POLYGON ((35 10, 45 45, 15 40, 10 20, 35 10), (20 30, 35 35, 30 20, 20 30))'` would have two df's ?

**Comment by Ironholds** [comment]
Indeed, hence why it sounds ah. Less than preferable.

**Comment by sckott** [comment]
Okay, let's go with the first option you suggested then

>wicket::wkt_coords('POLYGON ((35 10, 45 45, 15 40, 10 20, 35 10), (20 30, 35 35, 30 20, 20 30))')
>
>    entry layer lon lat
> 1  1 outer 35  10
> 2  1 outer 45  45
> 3  1 outer 15  40
> 4  1 outer 10  20
> 5  1 outer 35  10

**Comment by Ironholds** [comment]
Can do.

**Comment by Ironholds** [comment]
Okay, except you can have *multiple* rings in the inner layer. Do you not mind if all the rings are mingled together, just so long as they're evaluated as inner, or?

**Comment by sckott** [comment]
Is it too difficult to separate the inner rings?

**Comment by Ironholds** [comment]
Nope, but what do you want as the names in `layer`? outer, inner, inner_2, inner_3..?

**Comment by sckott** [comment]
yeah, that makes sense, with the number, 1,2, 3, etc.

**Comment by Ironholds** [comment]
Alrighty; test now?

**Comment by sckott** [comment]
gives back data from the first polygon for both of them

```r
wicket::wkt_coords("POLYGON((-125 38.4, -121.8 38.4, -121.8 40.9, -125 40.9, -125 38.4), (-115 22.4, -111.8 22.4, -111.8 30.9, -115 30.9, -115 22.4))")
#>    object    ring  lat    lng
#> 1       1   outer 38.4 -125.0
#> 2       1   outer 38.4 -121.8
#> 3       1   outer 40.9 -121.8
#> 4       1   outer 40.9 -125.0
#> 5       1   outer 38.4 -125.0
#> 6       1 inner 1 38.4 -125.0
#> 7       1 inner 1 38.4 -121.8
#> 8       1 inner 1 40.9 -121.8
#> 9       1 inner 1 40.9 -125.0
#> 10      1 inner 1 38.4 -125.0
```

**Comment by Ironholds** [comment]
Thaaat's weird. I'll play with the code; thankee!

**Comment by Ironholds** [comment]
Try now?

**Comment by sckott** [comment]
no new commits :)

**Comment by Ironholds** [comment]
Thaaat's weird. Now? :D

**Comment by sckott** [comment]
sweet, work good
