### ISSUE TITLE
centroid

### ISSUE THREAD

**Issue by sckott** [ropensci/wicket#11]
http://www.boost.org/doc/libs/1_47_0/libs/geometry/doc/html/geometry/reference/algorithms/centroid/centroid_2.html

another issue is i sometimes need to calculate centroid for WKT, doing this now with a Turf JS module https://github.com/ropensci/spocc/blob/master/inst/js/turf-centroid.js - but if can be added here easily, then ....

**Comment by Ironholds** [comment]
2D or 3D centroid?

**Comment by Ironholds** [comment]
Also at this point on a practical basis the hours have hit their limit, so I guess this would go into the ongoing-maintenance-and-new-features contract?

**Comment by sckott** [comment]
yeah, onto the new contract if all hrs up on 1st. 

just 2D

**Comment by Ironholds** [comment]
Do you want universal support or just polygon support?

**Comment by sckott** [comment]
universal if doable, for 2D that is

**Comment by Ironholds** [comment]
Should now be testable as `get_centroid` (although I need to write tests)

**Comment by sckott** [comment]
Seems to work so far for polygons - does it only support `POLYGON` right now?

**Comment by Ironholds** [comment]
Right now, yes, but I can widen it out to the other supported types trivially (obviously GCs are...harder to do, but everything *else*..)

**Comment by sckott** [comment]
thanks, skipping GC seems good to me

**Comment by Ironholds** [comment]
Test now?

**Comment by sckott** [comment]
working on it

**Comment by sckott** [comment]
works good AFAICT
