### ISSUE TITLE
invalid WKT in example, rendered valid by wicket.

### ISSUE THREAD

**Issue by edzer** [ropensci/wicket#13]
`?wkt_centroid` gives `POLYGON((2 1.3,2.4 1.7))` as an example, and
```
> validate_wkt("POLYGON((2 1.3,2.4 1.7))")
  is_valid comments
1     TRUE     <NA>
```
I don't believe that this is a valid polygon, though. WKT polygons need to be closed, and span an area.

With `sf`:
```
> st_is_valid(st_as_sfc("POLYGON((2 1.3,2.4 1.7))"))
Error in CPL_geos_is_valid(st_geometry(x)) : 
  IllegalArgumentException: Points of LinearRing do not form a closed linestring
```

**Comment by Ironholds** [comment]
I'll raise it with the boost::geometry folks, although validation is mostly to check that the contents can be parsed out.

**Comment by edzer** [comment]
Then maybe you should call it `is_parseable` rather than `is_valid` - _valid_ has a different meaning in the context of the simple feature standard.

**Comment by Ironholds** [comment]
Hence why I've opened an upstream ticket to see why this is parsing as an acceptable polygon.

**Comment by Ironholds** [comment]
Still waiting on a response; will bump it.
