### ISSUE TITLE
New CRAN release

### ISSUE THREAD

**Issue by Ironholds** [ropensci/wicket#18]
When the other issues are fixed.

**Comment by Ironholds** [comment]
@sckott shout out if you want anything else integrated before the next release.

**Comment by sckott** [comment]
Okay, still traveling, will test more and get back to you.

**Comment by sckott** [comment]
tests with 1 of the 2 pkgs complete, all good - moving on to other one

**Comment by sckott** [comment]
@Ironholds working well on the other pkg, good to go AFAIK

**Comment by Ironholds** [comment]
Excellent! It may have to wait a bit; CRAN just put in a new rule about function registration, and Rcpp is yet to support it.

**Comment by sckott** [comment]
where is that?

**Comment by Ironholds** [comment]
See https://stat.ethz.ch/pipermail/r-devel/2017-February/073755.html

**Comment by Ironholds** [comment]
And now done! CC @sckott
