### ISSUE TITLE
new cran release?

### ISSUE THREAD

**Issue by sckott** [ropensci/wicket#21]
not sure of your plans @Ironholds  for next release. hoping to use `wkt_correct` in some pkgs, which is currently only in dev version here

**Comment by Ironholds** [comment]
I didn't realise I hadn't released a new one; my apologies. I'll get it out over the next couple of weeks unless it's more-urgent?

**Comment by sckott** [comment]
Sounds good

**Comment by Ironholds** [comment]
Done!
