### ISSUE TITLE
Add method for reverse

### ISSUE THREAD

**Issue by sckott** [ropensci/wicket#22]
https://www.boost.org/doc/libs/1_67_0/libs/geometry/doc/html/geometry/reference/algorithms/reverse.html

I needed this for a specific use case but it's probably useful in general, started here  https://github.com/ropensci/wicket/tree/reverse 

@Ironholds okay if i merge this after filling out and adding more tests ?

**Comment by Ironholds** [comment]
Go for it!

**Comment by sckott** [comment]
thanks
