### ISSUE TITLE
optionally toggle what validations are done with `validate_wkt()`

### ISSUE THREAD

**Issue by sckott** [ropensci/wicket#23]
immediate use case is for GBIF polygons need to be left winding, so walking counterclockwise and the stuff to the left is inside the polygon - whereas `boost::geometry::failure_wrong_orientation` pops up saying that it is wrong. 

perhaps put a param in `validate_wkt` to toggle what checks are done

**Comment by Ironholds** [comment]
Is this an ask for me or a note to self?

**Comment by sckott** [comment]
note to self, but also discussion. maybe it's a bad idea to be able to toggle different validation tests? seems like it okay as long as its documented well wherever someone implements it

**Comment by Ironholds** [comment]
Agreed on fine-if-doc'd!
