### ISSUE TITLE
Package lifecycle?

### ISSUE THREAD

**Issue by maelle** [ropensci/wicket#28]
:wave: @Ironholds @sckott!

Is this package actively maintained? As it seems to be a [legacy acquired package](https://devguide.ropensci.org/curationpolicy.html#legacy-acquired-packages), should it be transferred to a personal account? It might be in scope for software review, but I'm not sure what the overlap with wellknown is. _You two_ know the topic well, I do not. :grin: :see_no_evil: 

If you don't answer within one month, I'll transfer the repository to ropensci-archive, after which you could still email me to transfer the repo to a personal account.

Thank you!

**Comment by sckott** [comment]
No, not maintained, and archived on cran too. moving to archive sounds good to me
