### ISSUE TITLE
consistency in bounding box ordering

### ISSUE THREAD

**Issue by sckott** [ropensci/wicket#8]
* `bounding_wkt` expects min_x, max_x, min_y, max_y
* `wkt_bounding` gives data back in min_x min_y max_x max_y

could these be in consistent order?

I don't think there's one golden standard for bounding boxes, but 

* [GeoJSON spec](https://tools.ietf.org/html/rfc7946#page-12) has  west, south, east, north
* [OSM](http://wiki.openstreetmap.org/wiki/Bounding_Box) has left,bottom,right,top

so those two are at least consistent

**Comment by sckott** [comment]
@Ironholds seems to not be totally fixed, with newest version:

```r
<r> bounding_wkt(values = list(c(10, 12, 14, 16)))
#> [1] "POLYGON((10 14,10 16,12 16,12 14,10 14))"
<r> bounding_wkt(10, 12, 14, 16)
#> [1] "POLYGON((10 12,10 16,14 16,14 12,10 12))"
```

**Comment by Ironholds** [comment]
Oooh, that's weird. Okay, will work on.

**Comment by Ironholds** [comment]
New version:

library(wicket)
> bounding_wkt(values = list(c(10, 12, 14, 16)))
[1] "POLYGON((10 12,10 16,14 16,14 12,10 12))"
> bounding_wkt(10, 12, 14, 16)
[1] "POLYGON((10 12,10 16,14 16,14 12,10 12))"
